const a_number_integer = 10;
const a_number_float = 10.5;
const a_string = "This is my cell phone";
const a_boolean_isAdmin = true;
const a_boolean_isActive = false;
let a_null =null;
let a_undefined;
console.log(typeof a_number_integer);
console.log(typeof a_number_float);
console.log(typeof a_string);
console.log(typeof a_boolean_isAdmin);
console.log(typeof a_boolean_isActive);
console.log(typeof a_null);    
console.log(typeof a_undefined);
